### ISSUE TITLE
Document the steps the client has to do and give them access

### ISSUE THREAD

**Issue by NicolasKP-EC** [digitc1/aadconsolidation#5]
Make available and presentable the information we already have
Test readme and Github wiki

**Comment by augustincolle-digit** [comment]
Uploaded readme and faq to github.
@NicolasKP-EC : The faq still need to be reviewed and updated. If you have any additional question, we can add them to the faq, otherwise please review the answers given and tell me if some require more explanations

**Comment by NicolasKP-EC** [comment]
Commited some fixes and I forgot to reference this issue ;).
